export const mobilePlatformMenu = [
  {
    _id: 'platform',
    condition: 'internal',
    url: '/platform',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Platform',
    hasSeparator: true,
    label: 'Overview',
    isListItem: false,
  },
  {
    _id: 'builder',
    condition: 'internal',
    url: '/builder',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Builder',
    hasSeparator: true,
    label: 'Website & Landing Page Builder',
    isListItem: false,
  },
  {
    _id: 'conversion-tools',
    condition: 'internal',
    url: '/conversion-tools',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Conversion Tools',
    hasSeparator: true,
    label: 'Conversion Tools',
    isListItem: false,
  },
  {
    _id: 'leads',
    condition: 'internal',
    url: '/leads',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Leads',
    hasSeparator: true,
    label: 'Leads',
    isListItem: false,
  },
  {
    _id: 'integrations',
    condition: 'internal',
    url: '/platform/integrations',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Integrations',
    hasSeparator: true,
    label: 'Integrations',
    isListItem: false,
  },
  {
    _id: 'templates',
    condition: 'internal',
    url: '/platform/templates',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Templates',
    hasSeparator: false,
    label: 'Templates',
    isListItem: false,
  },
]

export const mobileExpertiseMenu = [
  {
    _id: 'marketing-resources',
    condition: 'internal',
    url: '/marketing-resources',
    ariaLabel: 'Resource Library',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Resource Library',
  },
  {
    _id: 'blog',
    condition: 'internal',
    url: '/blog',
    ariaLabel: 'Leadpages blog',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Blog',
  },
  {
    _id: 'podcast',
    condition: 'internal',
    url: '/podcast',
    ariaLabel: 'Leadpages Podcast',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Podcast',
  },
  {
    _id: 'webinars',
    condition: 'internal',
    url: '/webinars',
    ariaLabel: 'Leadpages Webinars',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Webinars',
  },
  {
    _id: 'customers',
    condition: 'internal',
    url: '/customers',
    ariaLabel: 'Leadpages Customers',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Customer Stories',
  },
  {
    _id: 'hire-a-pro',
    condition: 'external',
    url: 'https://business.fiverr.com/certified/partners/leadpages?utm_source=fiverr_certified&utm_medium=leadpages&utm_campaign=leadpages',
    ariaLabel: 'Hire a Pro',
    rel: 'noopener',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Hire a Pro',
  },
  {
    _id: 'support',
    condition: 'external',
    url: 'https://support.leadpages.com/',
    ariaLabel: 'Leadpages support',
    rel: 'noopener',
    dataGtm: 'mobile-menu-link',
    hasSeparator: false,
    label: 'Support',
  },
]

export const mobileUseCasesMenu = [
  {
    _id: 'email-marketing',
    condition: 'internal',
    url: '/use-cases/email-marketing',
    ariaLabel: 'Email Marketing',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Email Marketing',
  },
  {
    _id: 'paid-ads',
    condition: 'internal',
    url: '/use-cases/paid-ads',
    ariaLabel: 'Paid Ads',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Paid Ads',
  },
  {
    _id: 'small-business-websites',
    condition: 'internal',
    url: '/use-cases/small-business-websites',
    ariaLabel: 'Small Business Websites',
    dataGtm: 'mobile-menu-link',
    hasSeparator: false,
    label: 'Small Business Websites',
  },
]

export const mobileTemplatesMenu = [
  {
    _id: 'templates',
    condition: 'internal',
    url: '/templates',
    ariaLabel: 'Landing Page Templates',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Landing Page Templates',
  },
  {
    _id: 'website-templates',
    condition: 'internal',
    url: '/website-templates',
    ariaLabel: 'Website Templates',
    dataGtm: 'mobile-menu-link',
    hasSeparator: false,
    label: 'Website Templates',
  },
]
