export const mobilePlatformMenu = [
  {
    _id: 'platform',
    condition: 'internal',
    url: '/platform',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Platform',
    hasSeparator: true,
    label: 'Overview',
    isListItem: false,
  },
  {
    _id: 'builder',
    condition: 'internal',
    url: '/platform/landing-page-builder',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Builder',
    hasSeparator: true,
    label: 'Landing Page Builder',
    isListItem: false,
  },
  {
    _id: 'conversion-tools',
    condition: 'internal',
    url: '/conversion-tools',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Conversion Tools',
    hasSeparator: true,
    label: 'Conversion Tools',
    isListItem: false,
  },
  {
    _id: 'leads',
    condition: 'internal',
    url: '/lead-management',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Leads',
    hasSeparator: true,
    label: 'Lead Management',
    isListItem: false,
  },
  {
    _id: 'integrations',
    condition: 'internal',
    url: '/platform/integrations',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Integrations',
    hasSeparator: true,
    label: 'Integrations',
    isListItem: false,
  },
  {
    _id: 'templates',
    condition: 'internal',
    url: '/platform/landing-page-templates',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Templates',
    hasSeparator: true,
    label: 'Landing Page Templates',
    isListItem: false,
  },
  {
    _id: 'blogs',
    condition: 'internal',
    url: '/platform/blogs',
    dataGtm: 'mobile-menu-link',
    ariaLabel: 'Blog',
    hasSeparator: false,
    label: 'Blogs',
    isListItem: false,
  },
]

export const mobileExpertiseMenu = [
  {
    _id: 'marketing-resources',
    condition: 'internal',
    url: '/marketing-resources',
    ariaLabel: 'Resource Library',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Resource Library',
  },
  {
    _id: 'blog',
    condition: 'internal',
    url: '/blog',
    ariaLabel: 'Leadpages blog',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Blog',
  },
  {
    _id: 'podcast',
    condition: 'external',
    url: '/podcast',
    ariaLabel: 'Leadpages Podcast',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Podcast',
  },
  {
    _id: 'webinars',
    condition: 'external',
    url: '/webinars',
    ariaLabel: 'Leadpages Webinars',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Webinars',
  },
  {
    _id: 'customers',
    condition: 'internal',
    url: '/customers',
    ariaLabel: 'Leadpages Customers',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Customer Stories',
  },
  {
    _id: 'support',
    condition: 'external',
    url: 'https://support.leadpages.com/',
    ariaLabel: 'Leadpages support',
    rel: 'noopener',
    dataGtm: 'mobile-menu-link',
    hasSeparator: false,
    label: 'Support',
  },
]

export const mobileServicesMenu = [
  {
    _id: 'all-services',
    condition: 'internal',
    url: '/services',
    ariaLabel: 'All Services',
    dataGtm: 'mobile-menu-link',
    label: 'All Services',
    hasSeparator: true,
  },
  {
    _id: '10-leads-60-days',
    condition: 'external',
    url: '/10-leads-60-days',
    ariaLabel: '10 Leads in 60 Days ',
    dataGtm: 'mobile-menu-link',
    label: '10 Leads in 60 Days ',
    hasSeparator: true,
  },
  {
    _id: 'monthly-coaching',
    condition: 'external',
    url: '/monthly-coaching',
    ariaLabel: 'Monthly Coaching',
    dataGtm: 'mobile-menu-link',
    label: 'Monthly Coaching',
    hasSeparator: true,
  },
  {
    _id: 'onboarding-call',
    condition: 'internal',
    url: '/onboarding-call ',
    ariaLabel: 'Onboarding Calls',
    dataGtm: 'mobile-menu-link',
    label: 'Onboarding Calls',
    hasSeparator: true,
  },
  {
    _id: 'hire-a-pro',
    condition: 'external',
    url: '/hire-a-pro',
    ariaLabel: 'Hire a Pro',
    dataGtm: 'mobile-menu-link',
    label: 'Hire a Pro',
    hasSeparator: false,
  },
]

export const mobileTemplatesMenu = [
  {
    _id: 'templates',
    condition: 'internal',
    url: '/templates',
    ariaLabel: 'Landing Page Templates',
    dataGtm: 'mobile-menu-link',
    hasSeparator: true,
    label: 'Landing Page Templates',
  },
  {
    _id: 'website-templates',
    condition: 'internal',
    url: '/website-templates',
    ariaLabel: 'Website Templates',
    dataGtm: 'mobile-menu-link',
    hasSeparator: false,
    label: 'Website Templates',
  },
]
