import { createStitches, defaultThemeMap } from '@stitches/react'
import {
  colors,
  space,
  spacing,
  mediaQueries,
  breakpoints,
  utils,
  borders,
  borderWidths,
  form,
  grid,
  sizes,
  shadows,
  transitions,
  easing,
  duration,
  radii,
  zIndices,
  type,
  magicNumbers,
} from './tokens'
import {
  pxToRem,
  getBoxSpacing,
  getAlignment,
  getTypeSizes,
  getTypeStyles,
  getType,
  getRatioStyles,
  getSizes,
} from './utils'

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors,
    space,
    form,
    grid,
    shadows,
    duration,
    easing,
    transitions,
    sizes,
    radii,
    zIndices,
    borderWidths,
    borders,
    breakpoints,
    ...spacing,
    ...magicNumbers,
    ...type,
  },
  media: mediaQueries,
  utils: {
    ...utils,
    box: (values) => getBoxSpacing(values),
    align: (values) => getAlignment(values),
    ratio: (ratio) => getRatioStyles(ratio),
    type: (variant) => getType(variant),
    typeSizes: (variant) => getTypeSizes(variant),
    typeStyles: (variant) => getTypeStyles(variant),
    sizeArray: (array) => getSizes(array),
  },
  themeMap: {
    ...defaultThemeMap,
    border: 'borders',
    borderTop: 'borders',
    borderBottom: 'borders',
    borderLeft: 'borders',
    borderRight: 'borders',
    'transition-timing-function': 'ease',
    'transition-duration': 'duration',
  },
})
export { pxToRem, breakpoints }
