export const platformSubMenu = [
  {
    _id: 'platform',
    condition: 'internal',
    url: '/platform',
    dataGtm: 'desktop-menu-link',
    label: 'Overview',
    isListItem: false,
  },
  {
    _id: 'builder',
    condition: 'internal',
    url: '/platform/landing-page-builder',
    dataGtm: 'desktop-menu-link',
    label: 'Landing Page Builder',
    isListItem: false,
  },
  {
    _id: 'conversion-tools',
    condition: 'internal',
    url: '/conversion-tools',
    dataGtm: 'desktop-menu-link',
    label: 'Conversion Tools',
    isListItem: false,
  },
  {
    _id: 'leads',
    condition: 'internal',
    url: '/lead-management',
    dataGtm: 'desktop-menu-link',
    label: 'Lead Management',
    isListItem: false,
  },
  {
    _id: 'integrations',
    condition: 'internal',
    url: '/platform/integrations',
    dataGtm: 'desktop-menu-link',
    label: 'Integrations',
    isListItem: false,
  },
  {
    _id: 'templates',
    condition: 'internal',
    url: '/platform/landing-page-templates',
    dataGtm: 'desktop-menu-link',
    label: 'Landing Page Templates',
    isListItem: false,
  },
  {
    _id: 'blogs',
    condition: 'internal',
    url: '/platform/blogs',
    dataGtm: 'desktop-menu-link',
    label: 'Blogs',
    isListItem: false,
  },
]

export const servicesSubMenu = [
  {
    _id: 'all-services',
    condition: 'internal',
    url: '/services',
    ariaLabel: 'All Services',
    dataGtm: 'desktop-menu-link',
    label: 'All Services',
  },
  {
    _id: '10-leads-60-days',
    condition: 'external',
    url: '/services/30-leads-30-days',
    ariaLabel: '30 Leads in 30 Days ',
    dataGtm: 'desktop-menu-link',
    label: '30 Leads in 30 Days ',
  },
  {
    _id: 'monthly-coaching',
    condition: 'external',
    url: '/services/monthly-coaching',
    ariaLabel: 'Monthly Coaching',
    dataGtm: 'desktop-menu-link',
    label: 'Monthly Coaching',
  },
  {
    _id: 'onboarding-call',
    condition: 'internal',
    url: '/services/onboarding-call ',
    ariaLabel: 'Onboarding Calls',
    dataGtm: 'desktop-menu-link',
    label: 'Onboarding Calls',
  },
  {
    _id: 'hire-a-pro',
    condition: 'external',
    url: '/hire-a-pro',
    ariaLabel: 'Hire a Pro',
    dataGtm: 'desktop-menu-link',
    label: 'Hire a Pro',
  },
]

export const templatesSubMenu = [
  {
    _id: 'templates',
    condition: 'internal',
    url: '/templates',
    ariaLabel: 'Landing Page Templates',
    dataGtm: 'desktop-menu-link',
    label: 'Landing Page Templates',
  },
  {
    _id: 'website-templates',
    condition: 'internal',
    url: '/website-templates',
    ariaLabel: 'Website Templates',
    dataGtm: 'desktop-menu-link',
    label: 'Website Templates',
  },
]

export const expertiseSubMenu = [
  {
    _id: 'marketing-resources',
    condition: 'internal',
    url: '/marketing-resources',
    ariaLabel: 'Resource Library',
    dataGtm: 'desktop-menu-link',
    label: 'Resource Library',
  },
  {
    _id: 'blog',
    condition: 'internal',
    url: '/blog',
    ariaLabel: 'Blog',
    dataGtm: 'desktop-menu-link',
    label: 'Blog',
  },
  {
    _id: 'podcast',
    condition: 'external',
    url: '/podcast',
    ariaLabel: 'Podcast',
    dataGtm: 'desktop-menu-link',
    label: 'Podcast',
  },
  {
    _id: 'webinars',
    condition: 'external',
    url: '/webinars',
    ariaLabel: 'Webinars',
    dataGtm: 'desktop-menu-link',
    label: 'Webinars',
  },
  {
    _id: 'customers',
    condition: 'internal',
    url: '/customers',
    ariaLabel: 'Customer Stories',
    dataGtm: 'desktop-menu-link',
    label: 'Customer Stories',
  },
  {
    _id: 'support',
    condition: 'external',
    url: 'https://support.leadpages.com',
    rel: 'noopener',
    ariaLabel: 'Support',
    dataGtm: 'desktop-menu-link',
    label: 'Support',
  },
]
