import {
  pink,
  purple,
  mauve,
  blue,
  red,
  green,
  yellow,
  blackA,
  whiteA,
} from '@radix-ui/colors'

export const colors = {
  ...blue,
  ...yellow,
  ...red,
  ...green,
  ...mauve,
  ...pink,
  ...purple,
  ...blackA,
  ...whiteA,
  gray: '#f9f9f9',
  tan: '#fef9f1',
  white: '#ffffff',
  black: '#000000',
  purple: '#603eff',
  purpleLight: '#d1c6f9',
  brand: '$purple10',
  primary: '$purple',
  secondary: '$purpleLight',
  buttonText: '$white',
  buttonBackground: '$brand',
  text: '#0f0c09',
  textAlt: '#575452',
  background: '$gray',
  backgroundAlt: '$tan',
  backgroundContrast: '$mauve3',
  border: '$purple10',
  link: '$primary',
  hover: '$purple8',
  focus: '$hover',
  active: '$hover',
  formFocus: '$brand',
  navText: '$text',
  navBackground: '$white',
  footerBackground: '$grey5',
  footerText: '$white',
  success: '$green5',
  error: '$red10',
  disabled: '$mauve8',
  warning: '$yellow4',
  overlay: '$blackA3',
  overlayA: '$whiteA3',
  progressBackground: '$blackA9',
  gradientBrand: 'linear-gradient(12deg, $colors$primary, $colors$secondary)',
  gradientBackgroundOpacity:
    'linear-gradient(to right, $colors$background, transparent)',
}

export default colors
