import {
  pink,
  purple,
  mauve,
  blue,
  red,
  green,
  yellow,
  blackA,
  whiteA,
  gray,
} from '@radix-ui/colors'

export const colors = {
  ...blue,
  ...yellow,
  ...red,
  ...green,
  ...mauve,
  ...pink,
  ...purple,
  ...blackA,
  ...whiteA,
  ...gray,
  white: '#ffffff',
  gray: '#f9f9f9',
  grayAlt: '#f7f7f7',
  lightGray: '#edecec',
  lightGray2: '#e9e9e9',
  lightGray3: '#eAeAeA',
  darkGray2: '#c2c1c0',
  darkGray: '#bfbebd',
  darkGrayAlt: '#797f89',
  socialGray: '#878584',
  silver: '#C3C2C1',
  grayTertiary: '#b1bacc',
  grayTertiaryAlt: '#e6e9ef',
  tan: '#fef9f1',
  black: '#000000',
  purpleDark: '#4938C4',
  purple: '#603eff',
  purpleLight: '#d1c6f9',
  purpleHighlight: '#7051FF',
  lavender: '#D1C6F9',
  lavenderLight: '#E4DEFC',
  lavenderBlush: '#fcedf5',
  champagne: '#f4e3cc',
  magnolia: '#f1edfd',
  teal: '#43E0F0',
  tealLight: '#8FEFEF',
  tealLighter: '#C7F7F7',
  ctaPurple: '$lavenderLight',
  indigoDark: '#4d32cc',
  offWhite: 'rgba(255, 255, 255, 0.7)',
  terracottaLight: '#dfae78',
  lightBrown: '#b27e52',
  darkBlue: '#0b236d',
  navy: '#0b236d',
  brand: '$purple10',
  primary: '$purple',
  statCards: 'rgba(73, 56, 196, 0.6)',
  secondary: '$purpleLight',
  buttonText: '$white',
  buttonBackground: '$brand',
  text: '#0f0c09',
  textAlt: '#575452',
  textHighlight: '#e28f44',
  background: '$gray',
  backgroundAlt: '$tan',
  backgroundContrast: '$mauve3',
  border: '$gray5',
  link: '$primary',
  hover: '$indigoDark',
  hoverColor: '$white',
  hoverColorGhost: '$white',
  focus: '$hover',
  active: '$hover',
  hoverInverse: '$offWhite',
  focusInverse: '$indigoDark',
  activeInverse: '$indigoDark',
  formFocus: '$brand',
  navText: '$text',
  navBackground: '$white',
  footerBackground: '$grey5',
  footerText: '$white',
  success: '$green5',
  error: '$red10',
  disabled: '$mauve8',
  warning: '$yellow4',
  overlay: '$blackA3',
  overlayA: '$whiteA3',
  progressBackground: '$blackA9',
  gradientBrand: 'linear-gradient(12deg, $colors$primary, $colors$secondary)',
  gradientBackgroundOpacity:
    'linear-gradient(to right, $colors$background, transparent)',
  dropdown: '$white',
}

export default colors
