export const fonts = {
  '@font-face': [
    {
      fontFamily: 'Value Serif',
      src: `url("https://static.leadpages.com/fonts/valueserif/value-serif-bold.woff2") format("woff2"), url("https://static.leadpages.com/fonts/valueserif//value-serif-bold.woff") format("woff")`,
      fontWeight: 700,
      fontStyle: 'normal',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/black/apercu-black-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/black/apercu-black-pro.woff') format('woff')`,
      fontWeight: 900,
      fontStyle: 'normal',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/bold-italic/apercu-bold-italic-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/bold-italic/apercu-bold-italic-pro.woff') format('woff')`,
      fontWeight: 700,
      fontStyle: 'italic',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/bold/apercu-bold-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/bold/apercu-bold-pro.woff') format('woff')`,
      fontWeight: 700,
      fontStyle: 'normal',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/extralight-italic/apercu-extralight-italic-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/extralight-italic/apercu-extralight-italic-pro.woff') format('woff')`,
      fontWeight: 200,
      fontStyle: 'italic',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/extralight/apercu-extralight-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/extralight/apercu-extralight-pro.woff') format('woff')`,
      fontWeight: 200,
      fontStyle: 'normal',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/italic/apercu-italic-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/italic/apercu-italic-pro.woff') format('woff')`,
      fontWeight: 400,
      fontStyle: 'italic',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/light-italic/apercu-light-italic-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/light-italic/apercu-light-italic-pro.woff') format('woff')`,
      fontWeight: 300,
      fontStyle: 'italic',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/light/apercu-light-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/light/apercu-light-pro.woff') format('woff')`,
      fontWeight: 300,
      fontStyle: 'normal',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/medium/apercu-medium-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/medium/apercu-medium-pro.woff') format('woff')`,
      fontWeight: 500,
      fontStyle: 'normal',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/medium-italic/apercu-medium-italic-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/medium-italic/apercu-medium-italic-pro.woff') format('woff')`,
      fontWeight: 500,
      fontStyle: 'italic',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/regular/apercu-regular-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/regular/apercu-regular-pro.woff') format('woff')`,
      fontWeight: 400,
      fontStyle: 'normal',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/thin-italic/apercu-thin-italic-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/thin-italic/apercu-thin-italic-pro.woff') format('woff')`,
      fontWeight: 100,
      fontStyle: 'italic',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Apercu Pro',
      src: `url('https://static.leadpages.com/fonts/apercu/thin/apercu-thin-pro.woff2') format('woff2'), url('https://static.leadpages.com/fonts/apercu/thin/apercu-thin-pro.woff') format('woff')`,
      fontWeight: 100,
      fontStyle: 'normal',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Space Mono',
      src: `url("https://static.leadpages.com/fonts/spacemono/SpaceMono-Regular.ttf") format("truetype")`,
      fontWeight: 400,
      fontStyle: 'normal',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Space Mono',
      src: `url("https://static.leadpages.com/fonts/spacemono/SpaceMono-Bold.ttf") format("truetype")`,
      fontWeight: 700,
      fontStyle: 'normal',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Space Mono',
      src: `url("https://static.leadpages.com/fonts/spacemono/SpaceMono-BoldItalic.ttf") format("truetype")`,
      fontWeight: 700,
      fontStyle: 'italic',
      fontDisplay: 'swap',
    },
    {
      fontFamily: 'Space Mono',
      src: `url("https://static.leadpages.com/fonts/spacemono/SpaceMono-Italic.ttf") format("truetype")`,
      fontWeight: 400,
      fontStyle: 'italic',
      fontDisplay: 'swap',
    },
  ],
}
